name: superup
repository: https://github.com/hatemragab/superup

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:

  postbootstrap: cd packages/s_translation && flutter gen-l10n
  analyze:
    run: |
      melos exec -c 1 -- \
          dart analyze . --fatal-infos
  format:
    run: melos exec -c 1 -- \
      flutter format .
  fix:
    run: melos exec -c 1 -- \
      dart fix --apply