name: superup
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  get: 4.6.1
  textless:
  country_list_pick: ^1.0.1+5
  flutter_countdown_timer: ^4.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter:
  assets:
    - assets/images/
    - assets/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/privacy/
    - assets/profile_info/
  uses-material-design: true
  generate: true

flutter_icons:
  android: ic_launcher
  image_path: assets/logo.png
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: true