name: superup
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  get: 4.6.1
  textless: ^6.6.6
  country_list_pick: ^1.0.1+5
  story_view: ^0.13.2
  camera: ^0.9.4+19
  flutter_countdown_timer: ^4.1.0
  measured_size: ^1.0.0
  #Whats app packages
  status_view: ^0.0.2
  ionicons: ^0.1.2
  camera_with_files: ^0.0.4
  app_utils: ^0.0.4
  swipe_to: ^1.0.2
  # mentions
  easy_rich_text: ^1.0.4
  lightbox: ^0.1.0
  sliver_header_delegate: ^0.0.5
  customizable_space_bar: ^0.2.0
  chat_bubbles: ^1.2.0
  emoji_picker_flutter: ^1.1.2
  record: ^3.0.4
  stop_watch_timer: ^1.3.1
  permission_handler: ^9.2.0
  flutter_painter: ^1.0.1
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  flutter_video_info: ^1.2.0
  video_thumbnail: ^0.5.0
  flutter_native_image: ^0.0.6+1
  image_gallery_saver: ^1.7.1
  mime_type: ^1.0.0
  path_provider:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter:
  assets:
    - assets/images/
    - assets/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/privacy/
    - assets/profile_info/
    - assets/message/
  uses-material-design: true
  generate: true

flutter_icons:
  android: ic_launcher
  image_path: assets/logo.png
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: true