name: super_up
version: 0.0.1+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  story_view: ^0.14.0
  sliver_header_delegate: ^0.0.5
  customizable_space_bar: ^0.2.0
  custom_pop_up_menu: ^1.2.4
  ionicons: ^0.2.2
  camera: ^0.10.2+1
  v_chat_message_page: ^0.3.0
  v_chat_sdk_core: ^0.3.0+1
  v_chat_room_page: ^0.3.0
  v_chat_one_signal: ^0.3.0
  v_chat_utils: ^0.3.0
  badges: ^3.0.2
  responsive_framework: ^0.2.0
  status_view: ^0.0.2
  flex_color_scheme: ^6.1.2
  flutter_social_button: ^1.1.4
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  super_up_core:
    path: ../super_up_core

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  email_validator: ^2.1.17
  touchable_opacity: ^1.2.0
  v_chat_firebase_fcm: ^0.3.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.11.0
flutter:
  assets:
    - assets/images/
    - assets/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/privacy/
    - assets/profile_info/
    - assets/message/
    - .env
  uses-material-design: true
  generate: true

flutter_icons:
  android: ic_launcher
  image_path: assets/logo.png
  ios: true
  remove_alpha_ios: true
#  adaptive_icon_foreground: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
