name: super_up
version: 0.0.1+16
publish_to: none
description: Super up app is social media chat system whats app clone
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  yaml: ^3.1.1
  v_chat_web_rtc: ^0.7.0
  v_chat_message_page: ^0.7.0+1
  v_chat_sdk_core: ^0.7.0
  v_chat_room_page: ^0.7.0
  v_chat_one_signal: ^0.7.0
  v_chat_firebase_fcm: ^0.7.0
  v_chat_receive_share: ^0.7.0
  v_chat_utils: ^0.7.0
  cupertino_icons: ^1.0.5
  story_view: ^0.14.0
  customizable_space_bar: ^0.2.0
  custom_pop_up_menu: ^1.2.4
  ionicons: ^0.2.2
  camera: ^0.10.3
  badges: ^3.0.2
  responsive_framework: ^0.2.0
  status_view: ^0.0.2
  flutter_social_button: ^1.1.4+1
  firebase_core: ^2.7.0
  camera_android: ^0.10.4
  flex_color_scheme: ^7.0.0-dev.2
  http: ^0.13.5
  firebase_messaging: ^14.2.5
  super_up_core:
    path: ../../packages/super_up_core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  email_validator: ^2.1.17
  touchable_opacity: ^1.2.0
  flutter_dotenv: ^5.0.2
  settings_ui: ^2.0.2
  window_manager: ^0.3.1
  package_info_plus: ^3.0.3
  get_it: ^7.2.0
  url_strategy: ^0.2.0
  path_provider: ^2.0.13
dependency_overrides:
  camera_android: ^0.10.4
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.11.0
flutter:
  assets:
    - assets/images/
    - assets/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/privacy/
    - assets/profile_info/
    - assets/message/
    - .env
  uses-material-design: true
  generate: true

flutter_icons:
  android: ic_launcher
  image_path: assets/logo.png
  ios: true
  remove_alpha_ios: true
#  adaptive_icon_foreground: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
